CREATE TABLE IF NOT EXISTS CLIENT (
    ID BIGINT IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255) NOT NULL,
	PHONE VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS MECHANIC (
	ID BIGINT IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
	PATRONYMIC VARCHAR(255) NOT NULL,
	SALARY DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
	ID BIGINT IDENTITY PRIMARY KEY,
    DESCRIPTION VARCHAR(2000) NOT NULL,
	CLIENT BIGINT NOT NULL,
	MECHANIC BIGINT NOT NULL,
	CREATE_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PRICE DOUBLE NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	FOREIGN KEY (CLIENT) REFERENCES CLIENT(ID),
	FOREIGN KEY (MECHANIC) REFERENCES MECHANIC(ID)
);